### ISSUE TITLE
AivenClient requires all parameters to have same type

### ISSUE THREAD

**Issue by jongiddy** [ansrivas/aiven-rs#44]
AivenClient's `new` and `from_token` methods require all parameters to have type `T` when `T: Into<String>`. This restricts all parameters to use the same type. In the examples they are all `&str`. However, while `version` is likely to be `&str`, the other parameters may be `String` or similar types, depending on how they are obtained. To support different concrete types for these parameters, they should each have a different named generic type.

```
pub fn from_token<T, U, V>(base_url: U, version: V, token: T) -> AivenClient
	where
		T: Into<String>,
		U: Into<String>,
		V: Into<String>,
```

**Comment by ansrivas** [comment]
Hey, thanks for reporting this. I fixed this and will publish a new release soon.
